-- V9__Create_notifications_table.sql
-- Creates the notifications table for analytics alerts

CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    metric_value DECIMAL(15, 2),
    threshold_value DECIMAL(15, 2),
    comparison_period VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT chk_notification_type CHECK (type IN ('REVENUE_DROP', 'FAILED_TRANSACTION_SPIKE', 'HIGH_VOLUME_DAY', 'LOW_SUCCESS_RATE', 'HIGH_PENDING_TRANSACTIONS')),
    CONSTRAINT chk_notification_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

-- Indexes for efficient querying
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_type ON notifications(type);
CREATE INDEX idx_notifications_severity ON notifications(severity);

-- Composite index for unread notifications query (most common query)
CREATE INDEX idx_notifications_unread_recent ON notifications(is_read, created_at DESC) WHERE is_read = FALSE;

-- Add comment
COMMENT ON TABLE notifications IS 'Stores analytics notifications/alerts generated by the system based on threshold comparisons';
